### ISSUE TITLE
react-use-websocket package is broken since 7.1.19

### ISSUE THREAD

**Issue by RagibHasin** [vitejs/rolldown-vite#582]
### Describe the regression

A project using React, `react-use-websocket`, TansStack Router, TailwindCSS and DaisyUI used to work fine with `rolldown-vite@7.1.18`.
Since `rolldown-vite@7.1.19` it gives this error on page load:

> useWebSocket is not a function

I have `import useWebSocket from "react-use-websocket"` in my code.

### Reproduction

https://github.com/RagibHasin/rolldownd-problem-of-vite

### Expected Behavior

I expected it to work as usual.

### Actual Behavior

But it does some mis-bundling (!?).

### Steps to Reproduce

The repro repo has two commits. The first commit works fine. The second commit gives the error.

Steps to check are:

1. `pnpm i`
2. `pnpm run dev`

### System Info

```shell
System:
    OS: Windows 11 10.0.26200
    CPU: (8) x64 AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx
    Memory: 1.04 GB / 5.95 GB
  Binaries:
    Node: 25.5.0 - C:\Program Files\Volta\node.EXE
    npm: 11.8.0 - C:\Program Files\Volta\npm.EXE
    pnpm: 10.28.1 - C:\Users\Ragib\AppData\Local\Volta\bin\pnpm.CMD
    Deno: 2.6.5 - C:\Users\Ragib\AppData\Local\Microsoft\WinGet\Packages\DenoLand.Deno_Microsoft.Winget.Source_8wekyb3d8bbwe\deno.EXE
  Browsers:
    Edge: Chromium (143.0.3650.80)
    Firefox: 147.0.1 - C:\Program Files\Mozilla Firefox\firefox.exe
  npmPackages:
    @vitejs/plugin-react: ^5.1.2 => 5.1.2
    vite: v8.0.0-beta.10 => 8.0.0-beta.10
```

### Used Package Manager

pnpm

### Validations

- [x] Follow our [Code of Conduct](https://github.com/vitejs/rolldown-vite/blob/main/CODE_OF_CONDUCT.md)
- [x] Read the [Contributing Guidelines](https://github.com/vitejs/rolldown-vite/blob/main/CONTRIBUTING.md).
- [x] Read the [docs](https://vite.dev/guide) and the [Rolldown-related guide](https://main.vite.dev/guide/rolldown.html).
- [x] Check that there isn't [already an issue](https://github.com/vitejs/rolldown-vite/issues) that reports the same regression to avoid creating a duplicate.
- [x] Check that this is a concrete regression. For Q&A open a [GitHub Discussion](https://github.com/vitejs/rolldown-vite/discussions) or join our [Discord Chat Server](https://chat.vite.dev/).
- [x] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the regression.

**Comment by sapphi-red** [comment]
This is an expected behavior change.
See https://main.vite.dev/guide/migration#consistent-commonjs-interop
