### ISSUE TITLE
8.0.0-beta.2  import mermaid from 'mermaid' error

### ISSUE THREAD

**Issue by zhl1232** [vitejs/rolldown-vite#561]
### Describe the bug

Uncaught TypeError: require_dist is not a function<br>    at chunk-S3R3BYOJ-gH0En3Jn.js?v=6da93fe3:902:19

### Reproduction

[https://stackblitz.com/edit/vitejs-vite-up8d61et?file=src%2Fmain.js,package.json,index.html,vite.config.ts,src%2FMermaidView.vue&terminal=dev](<https://stackblitz.com/edit/vitejs-vite-up8d61et?file=src%2Fmain.js,package.json,index.html,vite.config.ts,src%2FMermaidView.vue&terminal=dev>)

### Steps to reproduce

*No response*

### System Info

```shell
//#region node_modules/.pnpm/mermaid@11.12.2/node_modules/mermaid/dist/chunks/mermaid.core/chunk-S3R3BYOJ.mjs
var import_dist = require_dist();

Uncaught TypeError: require_dist is not a function
    at chunk-S3R3BYOJ-gH0En3Jn.js?v=6da93fe3:902:19
```

### Used Package Manager

npm

### Logs

*No response*

### Validations

- [X] Follow our [Code of Conduct](<https://github.com/vitejs/rolldown-vite/blob/main/CODE_OF_CONDUCT.md>)
- [X] Read the [Contributing Guidelines](<https://github.com/vitejs/rolldown-vite/blob/main/CONTRIBUTING.md>).
- [X] Read the [docs](<https://vite.dev/guide>) and the [Rolldown-related guide](<https://main.vite.dev/guide/rolldown.html>).
- [X] Check that there isn't [already an issue](<https://github.com/vitejs/rolldown-vite/issues>) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](<https://github.com/vitejs/rolldown-vite/discussions>) or join our [Discord Chat Server](<https://chat.vite.dev/>).
- [X] The provided reproduction is a [minimal reproducible example](<https://stackoverflow.com/help/minimal-reproducible-example>) of the bug.

**Comment by TheAlexLichter** [comment]
Likely related to https://github.com/rolldown/rolldown/releases/tag/v1.0.0-beta.54. Seems to be caused by https://github.com/rolldown/rolldown/pull/7343.

Still works with https://github.com/rolldown/rolldown/commit/f20ce58a0394a94b51c2862e677a9e82f6ccab09 but breaks with https://github.com/rolldown/rolldown/commit/a244fb6790af63409194ecc71672984721dee49e

**Comment by IWANABETHATGUY** [comment]
Even though I disabled the chunk optimization, the issue still exists.

<img width="1148" height="300" alt="Image" src="https://github.com/user-attachments/assets/15c1d8b8-6a81-4912-806d-dea376c318d8" />

<img width="2542" height="635" alt="Image" src="https://github.com/user-attachments/assets/1a6405f5-467b-4f44-96f2-3b062dd8b9a4" />

**Comment by IWANABETHATGUY** [comment]
The root cause is that there is a circular reference in the final bundle. Probably it is related to dep Optimization? I am not sure.

**Comment by IWANABETHATGUY** [comment]
> Likely related to https://github.com/rolldown/rolldown/releases/tag/v1.0.0-beta.54. Seems to be caused by [rolldown/rolldown#7343](https://github.com/rolldown/rolldown/pull/7343).
> 
> Still works with [rolldown/rolldown@f20ce58](https://github.com/rolldown/rolldown/commit/f20ce58a0394a94b51c2862e677a9e82f6ccab09) but breaks with [rolldown/rolldown@a244fb6](https://github.com/rolldown/rolldown/commit/a244fb6790af63409194ecc71672984721dee49e)

I can still reproduce on a4dad2985c6c42d848b384ef0ce54e7a7724ddf1


<img width="2076" height="1305" alt="Image" src="https://github.com/user-attachments/assets/2c87ef2d-ead1-4b96-bc47-014f72a7bbd4" />
with disabling the cross_module_optimization directly

**Comment by sapphi-red** [comment]
@IWANABETHATGUY I guess you forgot to delete the cache (`node_modules/.vite`). It works with https://github.com/rolldown/rolldown/commit/f20ce58a0394a94b51c2862e677a9e82f6ccab09: https://stackblitz.com/edit/vitejs-vite-kx56giaa?file=src%2Fmain.js,index.html,vite.config.ts&terminal=dev

**Comment by IWANABETHATGUY** [comment]
> [@IWANABETHATGUY](https://github.com/IWANABETHATGUY) I guess you forgot to delete the cache (`node_modules/.vite`). It works with [rolldown/rolldown@f20ce58](https://github.com/rolldown/rolldown/commit/f20ce58a0394a94b51c2862e677a9e82f6ccab09): https://stackblitz.com/edit/vitejs-vite-kx56giaa?file=src%2Fmain.js,index.html,vite.config.ts&terminal=dev

Is there any way we could force-run dev without cache?

**Comment by sapphi-red** [comment]
If you run dev with `vite dev --force`, it'll rerun the dep optimization ignoring the cache.

**Comment by mlarabi** [comment]
This is still happening with 8.0.0-beta.6
Doesnt happen with rolldown-vite 7.3.0.

**Comment by mlarabi** [comment]
However I was able to "fix" the issue by adding this little bad boy in the vite config file:
```
    optimizeDeps: {
      rolldownOptions: {
        experimental: {
          strictExecutionOrder: true,
        },
      },
    },
```
I saw this as a fix somewhere for Storybook and its also the solution here for MermaidJS and Excalidraw packages to be bundled.
Also the issue happens only in dev mode. When building then serving the dist, there is no issue.

**Comment by sapphi-red** [comment]
Closing as this seems to work with 8.0.0-beta.15+.
