### ISSUE TITLE
Build cannot be server in v7 while it work in v6

### ISSUE THREAD

**Issue by riderx** [vitejs/rolldown-vite#383]
### Describe the regression

After upgrade to v7 the page served show this error in the console `TypeError: (void 0) is not a function. (In '(void 0)(`//`)', '(void 0)' is undefined)`
If I use normal Vite v7 it works, or rolldown v6.3.5
I tried to use enableNativePlugin true or false it's same

### Reproduction

https://github.com/Cap-go/capgo

### Expected Behavior

It should work as expected.

### Actual Behavior

TypeError: (void 0) is not a function. (In '(void 0)(`//`)', '(void 0)' is undefined)

### System Info

```shell
nodejs 22
```

### Used Package Manager

bun

### Logs

[debug.log](https://github.com/user-attachments/files/21880480/debug.log)

### Validations

- [x] Follow our [Code of Conduct](https://github.com/vitejs/rolldown-vite/blob/main/CODE_OF_CONDUCT.md)
- [x] Read the [Contributing Guidelines](https://github.com/vitejs/rolldown-vite/blob/main/CONTRIBUTING.md).
- [x] Read the [docs](https://vite.dev/guide) and the [Rolldown-related guide](https://main.vite.dev/guide/rolldown.html).
- [x] Check that there isn't [already an issue](https://github.com/vitejs/rolldown-vite/issues) that reports the same regression to avoid creating a duplicate.
- [x] Check that this is a concrete regression. For Q&A open a [GitHub Discussion](https://github.com/vitejs/rolldown-vite/discussions) or join our [Discord Chat Server](https://chat.vite.dev/).
- [x] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the regression.

**Comment by riderx** [comment]
Hey @sapphi-red could you guide me on how to make that as the problem give no leads on the issue and it work in dev mode.
So I have no idea what should I add to the reproduction.
Currently the reproduction It the repository itself that you can run very easily.
If  you know how I can bissect easily I would do the job right now it seems undoable to find what line of code break as the error give zero indication, what made it impossible for you as well ^^

**Comment by sapphi-red** [comment]
I guess enabling the sourcemap would make the stacktrace show the original code position. Disabling the minification can also make the output more readable so that you can map it back to the original code manually.

**Comment by riderx** [comment]
Yea I think so too ! 
I saw they merged the PR in OXC, that mean we will get the fix soon ?

**Comment by sapphi-red** [comment]
Yeah, I'd say within a few weeks.
