### ISSUE TITLE
Redux-persist no longer works in rolldown-vite 7.1.19

### ISSUE THREAD

**Issue by RichDom2185** [vitejs/rolldown-vite#457]
### Describe the regression

With `rolldown-vite` 7.1.18, `storage.getItem` used to work fine. Now it throws an error: `Uncaught TypeError: storage.setItem is not a function`

Note: Tested with latest Vite at the time of writing (7.1.11) and it works fine.

### Reproduction

https://stackblitz.com/edit/vitejs-rolldown-vite-vm6wdwjv?file=README.md

### Expected Behavior

It should work normally (reverting to 7.1.18 works fine), with redux-persist rehydrating the store (even if it's on the initial load without any persisted state)

### Actual Behavior

The entire app crashes due to the type error during store initialization

### Steps to Reproduce

1. Clone the linked StackBlitz
2. Notice the app will not start
3. View the above error message in the console/DevTools
4. Edit the version of rolldown-vite in package.json to 7.1.18
5. The app works

### System Info

```shell
NA, affecting all environments
```

### Used Package Manager

npm

### Validations

- [x] Follow our [Code of Conduct](https://github.com/vitejs/rolldown-vite/blob/main/CODE_OF_CONDUCT.md)
- [x] Read the [Contributing Guidelines](https://github.com/vitejs/rolldown-vite/blob/main/CONTRIBUTING.md).
- [x] Read the [docs](https://vite.dev/guide) and the [Rolldown-related guide](https://main.vite.dev/guide/rolldown.html).
- [x] Check that there isn't [already an issue](https://github.com/vitejs/rolldown-vite/issues) that reports the same regression to avoid creating a duplicate.
- [x] Check that this is a concrete regression. For Q&A open a [GitHub Discussion](https://github.com/vitejs/rolldown-vite/discussions) or join our [Discord Chat Server](https://chat.vite.dev/).
- [x] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the regression.

**Comment by sapphi-red** [comment]
Related: https://github.com/rolldown/rolldown/issues/6655
