### ISSUE TITLE
8.0.0-beta.13 build error

### ISSUE THREAD

**Issue by xxxx-p** [vitejs/rolldown-vite#595]
### Describe the bug

Background:
My project is a relatively old project with many commonJs dependencies. After modifying legacy. InconsistentCjsInterop to true, the production version was built and ran normally in version 8.0.0-beta.10.

Problem: After upgrading to 8.0.0-beta.11-8.0-beta.13, building the production version reports an error:
chatSurvey-purify-CLffJMu0.js:1 Uncaught TypeError: e is not a function

The specific error file corresponds to the source code information:
import {xc as e} from "./chatSurvey-chatSurvey-Dz3uli48.js";
var t = e(( (e, t) => {
    (function(n, r) {

I tried to have AI analyze and ultimately successfully built the solution provided by AI

Reasons for AI analysis: Identify the issue: After using Rolldown with Vite 8, the "purify" chunk (from vue-dompurify-html) in chatSurvey is imported from the main chunk and called as a function. In beta.11, this export may be incorrectly named or not properly exposed. Provide two solutions
Merging vue-dompurify-html and dompurify into the main chunk of chatSurvey to avoid the "e is not a function" issue caused by incorrect splitting in Rolldown beta.11.

Ai's repair plan:
 rollupOptions.output.manualChunks: (id) => {
  if ((id.includes('vue-dompurify-html') || id.includes('dompurify'))) {
      return pageName
    }
  }

### Reproduction
Sorry, I tried to reproduce using the minimal application, but couldn't reproduce it. It was only present in the business project I encountered at the time. One difference is that the project in my business was quite large, and JS automatically split multiple files (without setting any manual splitting code, with Vite default configuration control). Therefore, I would like to ask if you can analyze the problem based on the above description. What I can confirm is that it was caused by the import of the dependency vue domain html

### System Info

```shell
vite:8.0.0-beta.13 node: 24.10.0
```

### Used Package Manager

pnpm

### Validations

- [x] Follow our [Code of Conduct](https://github.com/vitejs/rolldown-vite/blob/main/CODE_OF_CONDUCT.md)
- [x] Read the [Contributing Guidelines](https://github.com/vitejs/rolldown-vite/blob/main/CONTRIBUTING.md).
- [x] Read the [docs](https://vite.dev/guide) and the [Rolldown-related guide](https://main.vite.dev/guide/rolldown.html).
- [x] Check that there isn't [already an issue](https://github.com/vitejs/rolldown-vite/issues) that reports the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitejs/rolldown-vite/discussions) or join our [Discord Chat Server](https://chat.vite.dev/).
- [x] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sapphi-red** [comment]
It's impossible to investigate what is happening without a reproduction. But I assume it's a duplicate of https://github.com/vitejs/rolldown-vite/issues/597

**Comment by xxxx-p** [comment]
> [如果没有可复现的问题，就无法调查究竟发生了什么。但我推测它与#597](https://github.com/vitejs/rolldown-vite/issues/597)重复。[](https://github.com/vitejs/rolldown-vite/issues/597)

我今天升级到了最新版本，发现没有这个问题了
